### ISSUE TITLE
Introduce pre-commit hook and formatter

### ISSUE THREAD

**Issue by djs0109** [RWTH-EBC/FiLiP#341]
In order to simplify the review process, we should introduce the pre-commit hook with a formatter.

### requirements:
- pep 8 conform
- identical code length control
- what else?

### todos:
- [x] test the formatter locally
- [x] run formatter once for the current master branch, and check the results
- [x]  create pre-commit hook
- [x] update setup.py
- [x] update readme
